services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://<endpoint-db-prod>:5432/contasimplesmei
      SPRING_DATASOURCE_USERNAME: <usuario-prod>
      SPRING_DATASOURCE_PASSWORD: <senha-prod>
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
