services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/contasimplesmei
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  postgres:
    environment:
      POSTGRES_DB: contasimplesmei
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
