services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conta-simples-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contasimplesmei
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=contasimplesmei
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
