version: '3.8'

services:
  app:
    # Usar imagem do Docker Hub em vez de build local
    image: ${DOCKER_USERNAME}/myapp:latest
    container_name: myapp-staging
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - JAVA_OPTS=-Xmx400m -Xms128m -XX:MaxMetaspaceSize=64m
    restart: unless-stopped
    
    # Configurações para t2.micro
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: '0.8'
    
    # Health check otimizado
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    
    # Logs limitados para não encher o disco
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  default:
    name: myapp-network