spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/contasimplesmei_staging
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework: INFO