app:
  cors:
    allowed-origins: http://localhost:5173,https://contasimplesmei.com,https://www.contasimplesmei.com

spring:
  application:
    name: conta-simples-mei
  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: ${PORT:8080}

---
# Profile de desenvolvimento (local)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/contasimplesmei}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-url: ${DATABASE_URL}
    properties:
      hibernate:
        jdbc:
          url: ${DATABASE_URL}
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  cors:
    allowed-origins: http://localhost:5173

---
# Profile de produção (Railway)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/contasimplesmei}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-url: ${DATABASE_URL}
    properties:
      hibernate:
        jdbc:
          url: ${DATABASE_URL}
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
app:
  cors:
    allowed-origins: https://contasimplesmei.com,https://www.contasimplesmei.com