spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/contasimplesmei
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  logging:
    level:
      org.springframework: DEBUG
