server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contasimplesmei
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      password: dummy
