spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.springframework: WARN
  messages:
    basename: messages
    encoding: UTF-8