spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/contasimplesmei
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    banner-mode: off

logging:
  level:
    org.springframework: WARN